# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
# theme: minima
plugins:
  - jekyll-feed

menu:
  - category: 
    id: "project-stages"
    name: "Project Stages"
    subcategory: 
      - id: "discovery"
        name: "Discovery"
      - id: "design"
        name: "Design"
      - id: "prepare"
        name: "Prepare"
      - id: execute
        name: "Execute"
      - id: share
        name: "Share"
      - id: evaluate
        name: "Evaluate"
  - category:
    id: social-impact
    name: "Social Impact"
    subcategory: 
      - id: engineering
        name: "Engineering"
      - id: genai
        name: "GenAI"
      - id: governance
        name: "Governance"
      - id: scoping
        name: "Scoping"
  - category:
    id: volunteers
    name: "Volunteers"
    subcategory: 
      - id: getting-started
        name: "Getting Started"
      - id: donate
        name: "Donate"
      - id: chapter-operations
        name: "Chapter Operations"
      - id: volunteer-management
        name: "Volunteer Management"


include: ["_pages"]

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - old_html_site/
  - README.md
